### ISSUE TITLE
错误的submitfile2listofdict

### ISSUE THREAD

**Issue by chunqishi** [AllanYiin/bot2017Fin#1]
在 for i in range(1, len(lines) -1): 应该改成for i in range(1, len(lines)):
否则会少读一个数据

**Comment by AllanYiin** [comment]
是這樣的，因為這段是在讀取txt，由於第一row是字段名稱，因此改從index=1讀取，所以是從1到len(lines) -1。例如假設總共兩筆(一筆是字段名，一筆是內容)，這樣內容應該是只有一筆(len(lines)-1=2-1=1)

**Comment by chunqishi** [comment]
当然不对， 你知道range怎么用么？ 如果两行， 你从1开始到len(lines)-1也是1， 那么range(1,1), 兄弟，这个是空集。。。

**Comment by AllanYiin** [comment]
已修正
